echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27 and learning DevOps"
echo "Hello, goodmorning!"
echo "We are learning GitHub"
echo "hello hi from nagpur"
